#!/command/with-contenv bash

source /assets/functions/00-container
prepare_service
PROCESS_NAME="rspamd"

cat <<EOF

******************************************************************************************
*                                                                                        *
*                    END OF LIFE NOTICE AUGUST 18, 2025                                  *
*                               tiredofit/rspamd                                         *
*                                                                                        *
* This image is no longer maintained as of and will not receive updates.                 *
*                                                                                        *
* A successor image is available at:                                                     *
*                                                                                        *
* Repository | Documentation:                                                            *
*   - https://github.com/nfrastack/container-rspamd                                      *
*                                                                                        *
* Image Registries:                                                                      *
*   - https://hub.docker.com/r/nfrastack/rspamd                                          *
*   - https://github.com/nfrastack/container-rspamd/pkgs/container/container-rspamd      *
*                                                                                        *
* Please visit https://nfrastack.com for more information.                               *
*                                                                                        *
******************************************************************************************

EOF

sleep 15

if [ "${MODE,,}" = "aio" ] ; then
    configure_antivirus
    configure_asn
    configure_classifier_bayesian
    configure_controller
    configure_data_dir
    configure_dkim
    configure_dmarc
    configure_greylist
    configure_history
    configure_logging
    configure_milter
    configure_mx_check
    configure_neural
    configure_oletools
    configure_phishing
    configure_redis
    configure_reputation
    configure_rspamd_options
    configure_spamtrap
    configure_url_reputation
    configure_url_tags
    configure_worker_fuzzy
    configure_worker_proxy
    if var_nottrue "${SKIP_REDIS_HOST_CHECK}" ; then db_ready redis ; fi
    create_zabbix rspamd
else
    print_info "Setting to Spam Notify AGENT mode"
    service_stop 10-rspamd
fi

custom_scripts /assets/custom-scripts

liftoff
